!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
! must be included in order of dependence
#include "basicmodules.f"
#include "UTILS/statsmodule.f"
#include "UTILS/rvmodule.f"
#include "UTILS/pfmodule.f"
#include "UTILS/ellipticmodule.f"
#include "UTILS/zolomodule.f"
#include "UTILS/polyapproxmod.f"
#include "UTILS/extpolyapproxmod.f"
#include "UTILS/remezapproxmod.f"
#include "UTILS/ratfuncs.f"
#include "UTILS/utils.f"
#include "DIRAC_OPS/WilsonDirac.f"
#include "DIRAC_OPS/WilsonDiracExtra.f"
#include "DIRAC_OPS/ShamirDomainWall.f"
#include "DIRAC_OPS/WilsonDomainWall.f"
#include "DIRAC_OPS/domainwall.f"
#include "DIRAC_OPS/DomainWallPow.f"
#include "DIRAC_OPS/overlap.f"
#include "AUXFIELD/gaugefield.f"
!#include "AUXFIELD/hmc2wilsonferms.f"
#include "AUXFIELD/hmc2domwallferms.f"
#include "AUXFIELD/hmc2olferms.f"
#include "AUXFIELD/rhmc1domwallferm.f"
#include "AUXFIELD/gaugemodule.f"
#include "UTILS/IOmodule.f"
#include "MEASURE/cond.f"
!#include "CONDENSATE/condpointtools.f"
!#include "CONDENSATE/condnoisytools.f"
!#include "CONDENSATE/condensatetools.f"
!#include "CONDENSATE/condensate.f"
#include "kernelspectra.f"
#include "TESTS/testopequiv.f"
#include "allhmcmodules.f"
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
